### ISSUE TITLE
Need example for custom create-item slot

### ISSUE THREAD

**Issue by vicenterusso** [isneezy/vue-selectize#123]
I need example for changing the create-item slot:

```
<slot name="create-item" v-bind:text="searchText">
  Add <strong>{{ searchText }}</strong>...
</slot>
```
I tried:

```
<template v-slot:create-item="{item}">Custom text <strong>{{ item }}</strong></template>
```

But the text inside "strong" is not displayed. I tried all sort of variable names... "searchText", the v-model itself, etc.

**Comment by isneezy** [comment]
Hi thanks for filling this issue, please try this instead:

```vue
<template v-slot:create-item="{text}">Custom text <strong>{{ text }}</strong></template>
```
I did not test this but I hope it works, please give me feedback as I need to add this to the documentation
