### ISSUE TITLE
Add option to disable creating of new Item

### ISSUE THREAD

**Issue by solamichealolawale** [isneezy/vue-selectize#27]
**Is your feature request related to a problem? Please describe.**
There's no option to disable creating new Item on the component. Like I don't want the user to create a new item that is not on the list of option

**Describe the solution you'd like**
It will be nice if we have a prop like `:create="false"`

**Describe alternatives you've considered**
null

**Additional context**
null

**Comment by isneezy** [comment]
Thank you for tanking your time filling this Hi, jissue.  
Just can pass `:create-item="false"`

I'm closing this issue for now. but feel to comment and Ill reopen if necessary.
