### ISSUE TITLE
How to pass options

### ISSUE THREAD

**Issue by umardraz** [isneezy/vue-selectize#30]
Hello

How to pass some custom settings/options to selectize? Here is my code which is right now not working in nuxtjs

```
<VSelectize :options="owners" v-model="selected" :settings="customSettings" placeholder="Select owner" />

customSettings: {
                valueField: '_id',
                labelField: 'email'
            }

```
The problem is when I click on drop down button of select box then there is no option only a gray box is appear

**Comment by isneezy** [comment]
Hi, thanks for filling this issue, I'm sorry that the documentation is not clear enough, to instruct which key to use as label use the `label` prop and use `keyBy` prop to track the value as below

```vue
<VSelectize :options="owners" v-model="selected" key-by="_id" label="email" placeholder="Select owner" />
```
Also don't forget to import the selective.js css file

**Comment by umardraz** [comment]
Hello thanks for your reply, now the second issue is after add key-by and label the search is stop working, you can see in the following attachment, I tried to search user admin

<img width="234" alt="Screen Shot 2020-06-28 at 12 18 50 PM" src="https://user-images.githubusercontent.com/3677378/85941023-9efee200-b939-11ea-9b2d-e8af64f438dc.png">

**Comment by isneezy** [comment]
Simply use the prop `:keys="[''email']"` and add other properties that you want to be used on search

**Comment by umardraz** [comment]
Hi, thanks
One more thing that I want to share here, on mouseover the active class override the selected item background

**Comment by isneezy** [comment]
I'm glad to be helpful, note that contributions are always welcome here. I hope to receive you pull request to fix the mouseouver issue 🙂.

If you have any doubt please read the documentation at https://vue-selectize.vilanculo.me and there is a branch that I'm working on to improve it.

Looking forward to seeing your PR. ✌🏾

**Comment by umardraz** [comment]
Thanks for your help, it was great experience, I will wait the pull request :)
