### ISSUE TITLE
Update Readme to show Nuxt implementation

### ISSUE THREAD

**Issue by palashmon** [isneezy/vue-selectize#31]
**Is your feature request related to a problem? Please describe.**
Hi, thanks for this beautiful component. 

Just wanted to say, if you could please update the readme file to show how we can implement this component using [Nuxt.js](https://nuxtjs.org/). It would really help the beginners who want to learn or try out this component in their Nuxt applications without any hassle.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by isneezy** [comment]
Hi @palashmon, thanks for filling up this issue, and I'm also sorry for not having a good documentation, I'm working on a branch where I'm improving the documentation #29 

There is no difference on how you use with nuxt or with "vanila Vue.js"

What is the actual problem you are facing?

Please note, contributions are always welcome, feel free to send PR to help me improve this component.

**Comment by palashmon** [comment]
Actually, I had to spend lots of time to get it working like creating a new plugin in `~/plugins/vue-selectize.js` to register this component globally. Then register it in `nuxt.config.js` and also include the `selectize.css` from the CDN. I think if all the steps are documented then it would very helpful for future devs to implement it within a few minutes and move on.

**Comment by isneezy** [comment]
Ok, I feel your pain, would you mind making a PR for this? Since your mind is fresh and you already know all the steps and details... I'd appreciate it.

**Comment by palashmon** [comment]
Thanks so much. That is really helpful.

**Comment by isneezy** [comment]
Thanks for your feedback, in the meantime I'll create a Nuxt.js Module the Nuxt.js integration easier.
