### ISSUE TITLE
doesn't compile

### ISSUE THREAD

**Issue by N1Prop** [isneezy/vue-selectize#62]
**Describe the bug**
It doesn't compile.

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
```
ERROR in /node_modules/@isneezy/vue-selectize/dist/vue-selectize.common.js
Module parse failed: Unexpected token (5525:2)
You may need an appropriate loader to handle this file type.
| 
| var Config = {
|   ...BasicOptions,
|   ...MatchOptions,
|   ...FuzzyOptions,
```

**Comment by isneezy** [comment]
Hi @N1Prop, thanks for filling this issue. I've updated your issue to reflect our issue template.
Please update the steps to reproduce this issue so we'll be able to understand it and eventualy help you.
