### ISSUE TITLE
disableSearch disables search, but leaves input intact

### ISSUE THREAD

**Issue by bryanbuchs** [isneezy/vue-selectize#65]
**Describe the bug**
The `disableSearch` option disables the search function. However, the cursor is still focused on an empty text input, allowing the user to type with no feedback.  

**To Reproduce**
App:
https://codesandbox.io/s/charming-drake-gxqh4?file=/src/App.vue

Preview:
https://gxqh4.codesandbox.io/

1. Click or tab to activate the select 
2. Useless text field is focused

**Expected behavior**
When `disableSearch` prop is passed to component, the input should not be rendered, or at least disabled/hidden

**Desktop (please complete the following information):**
 - Windows
 - Firefox
 - 82.0b9

**Comment by isneezy** [comment]
Hi, thanks for filling the issue, as the documentation says, `disableSearch` only disables the built-in search engine, it is useful when you have search logic on your back-end for example.

To completely disable de input/component please use the prop `disabled`
https://vue-selectize.vilanculo.me/api/props.html#disabled

**Comment by isneezy** [comment]
@bryanbuchs here is a demo https://codesandbox.io/s/nice-goldstine-958kx?file=/src/App.vue let me know if you have any question.

**Comment by bryanbuchs** [comment]
Sorry, I was offline last week. That's not quite what I'm looking for. I would have thought `disableSearch` would remove the input since it's not needed. I don't want to actually disable the component. 

I'm looking for a simple no-dependency component to simply replace the browser's `select` element for style purposes. I'll either fork or keep looking. Thanks for the input!

**Comment by isneezy** [comment]
I understand what you're looking for, It does not support it but I'm willing to accept your PR for this functionality.
